### PR TITLE
Fix collapsed subscribers

### LINKED ISSUE #842: Event failing on multiple logical subscribers can results in data loss
### Symptoms
When an event is published to multiple logical subscribers and the message processing fails for more than one SC treats all failed messages as a single failed message and stores them in single document.  

As a result:
   * At any given moment in time the user sees only single failed message instead of all that actually failed
   * The users is able to request retry only for the message that failed most recently
   * Failed messages with status other than `Unresolved` get deleted after `Error Retention Policy` so any hidden, failed messages will get deleted without users knowing about it

### Who's Affected
Any version of ServiceControl prior to v1.27.0. with endpoints on version 5 and less.

### PR DESCRIPTION
**Pull request by mikeminutillo**
Fixes #842

### CODE REVIEW

File: src/ServiceControl.AcceptanceTests/MessageFailures/When_an_event_with_multiple_subscribers_fails.cs [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+                                else
+                                {
+                                    throw new Exception($"Unknown subscriber subscribed to publisher: {sub.SubscriberReturnAddress}");
+                                }
+                            })
+                        ).When(
+                            ctx => ctx.Subscriber1Subscribed && ctx.Subscriber2Subscribed,
+                            bus => bus.Publish<SampleEvent>()
+                        )
+                ).Done(ctx => TryGetMany("/api/errors", out failedMessages) && failedMessages.Count > 1)
```
Comment (SzymonPobiega) [inline src/ServiceControl.AcceptanceTests/MessageFailures/When_an_event_with_multiple_subscribers_fails.cs]: nitpicking: maybe better instead of `count > 1` use `count >= 2` to express that we expect at least two.

**Comment by SzymonPobiega** [comment]
LGTM

File: src/ServiceControl/Infrastructure/TransportMessageExtensions.cs [hunk 2]
```diff
@@ -16,18 +16,20 @@ public static string ProcessingEndpointName(this IReadOnlyDictionary<string, str
...
 
+            // This message could be a failed message.
+            if (headers.TryGetValue("NServiceBus.FailedQ", out endpoint))
+            {
+                return endpoint;
+            }
+
+            // In v5, a message that comes through the Audit Queue
+            // has it's ReplyToAddress overwritten to match the processing endpoint
             var replyToAddress = headers.ReplyToAddress();
```
Comment (ramonsmits) [inline src/ServiceControl/Infrastructure/TransportMessageExtensions.cs]: @mike can make sure that we only use this value in case of *audits*? Maybe to only use this value if no exception headers are present?

File: src/ServiceControl.AcceptanceTests/MessageFailures/When_a_retry_for_a_failed_message_is_successful.cs [hunk 3]
```diff
@@ -48,10 +48,9 @@ public void Should_show_up_as_resolved_when_doing_a_single_retry()
                 .Run(TimeSpan.FromMinutes(2));
 
             Assert.AreEqual(FailedMessageStatus.Resolved, failure.Status);
-            Assert.AreEqual(failure.UniqueMessageId, message.Id);
+            //Assert.AreEqual(failure.UniqueMessageId, message.Id);
```
Comment (johnsimons) [inline src/ServiceControl.AcceptanceTests/MessageFailures/When_a_retry_for_a_failed_message_is_successful.cs]: @mikeminutillo I had to comment this out to get this test to pass, not sure how this was ever working, any ideas ?

File: src/ServiceControl/Infrastructure/TransportMessageExtensions.cs (hunk 2 above)
Comment (mikeminutillo) [inline src/ServiceControl/Infrastructure/TransportMessageExtensions.cs]: @ramonsmits At the moment we'll only use ReplyToAddress if FailedQ is not present. All failed messages should have a FailedQ header. Should we still check for another header?

File: src/ServiceControl.AcceptanceTests/MessageFailures/When_a_retry_for_a_failed_message_is_successful.cs (hunk 3 above)
Comment (mikeminutillo) [inline src/ServiceControl.AcceptanceTests/MessageFailures/When_a_retry_for_a_failed_message_is_successful.cs]: @johnsimons actually, it did work because the results go through [this transformer](https://github.com/Particular/ServiceControl/blob/1ea1d2d566cd32463a3941a2c92ac36f781f72cd/src/ServiceControl/CompositeViews/Messages/MessagesViewTransformer.cs#L46) which sets the `message.Id` to the `FailedMessage.UniqueMessageId`. 

It no longer works because there is a discrepancy between the `UniqueMessageId` generated for the failing message versus the successful retry. The failing messages uses the `MessageId` and the `FailedQ` header to generate it's `UniqueMessageId`. The successful retry does not have a `FailedQ` header any more so it uses `MessageId` and `ReplyToAddress`.

In version 1.26 of ServiceControl, the failed message would have been using the `ReplyToAddress` as well so these would have matched. In a broker based transport where the `ReplyToAddress` and the `FailedQ` are likely to match, this is going to be less of an issue.

File: src/ServiceControl/DbMigrations/1.27/SplitFailedMessageDocumentsMigration.cs [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+            int retrievedResults;
+
+            var stats = new MigrationStats();
+
+            do
+            {
+                using (var session = store.OpenSession())
+                {
+
+                    var failedMessages = session.Advanced.LoadStartingWith<FailedMessage>(
```
Comment (mikeminutillo) [inline src/ServiceControl/DbMigrations/1.27/SplitFailedMessageDocumentsMigration.cs]: @tmasternak As soon as you add an orderby clause you aren't doing a load any more, you are doing a query. Doing a query in Raven requires that we add an index. I believe that `LoadStartingWith` should give us all of the documents in a deterministic order (insertion order?) but I can't find any doco proving that.
